#version 430 core

#ifdef PATH_TRACING
#include "tracePath.glsl"
#else
#include "traceSimple.glsl"
#endif

layout (local_size_x = 16, local_size_y = 16, local_size_z = 1) in;

// Output
layout(binding = 0, rgba32f) uniform writeonly image2D output_image;

// Uniforms
uniform uint dither_counter;
uniform mat4 cam_to_world;     // view-space -> world-space
uniform mat4 inv_projection;   // clip-space -> view-space
uniform int pixel_samples;

void main() {
    ivec2 pixel_coords = ivec2(gl_GlobalInvocationID.xy);
    ivec2 dims = imageSize(output_image);

    // Guard for oversized dispatch
    if (pixel_coords.x >= dims.x || pixel_coords.y >= dims.y) return;

    uint base_seed = uint(pixel_coords.x) * 1973u + uint(pixel_coords.y) * 9277u + dither_counter * 26699u;
    vec3 accumulated_color = vec3(0.0);

    for (int s = 0; s < pixel_samples; s++) {
        uint rng_state = pcg_hash(base_seed + uint(s) * 749u);

        // Jitter pixel position for anti-aliasing
        vec2 jitter = vec2(random_float(rng_state), random_float(rng_state)) - 0.5;

         // Pixel center -> Normalized Device Coordinates in [-1, 1] (with jitter)
        vec2 uv = (vec2(pixel_coords) + 0.5 + jitter) / vec2(dims);
        vec2 ndc = uv * 2.0 - 1.0;

        vec4 p_near_view = inv_projection * vec4(ndc, -1.0, 1.0); p_near_view /= p_near_view.w;
        vec4 p_far_view = inv_projection * vec4(ndc, 1.0, 1.0); p_far_view  /= p_far_view.w;

        vec3 origin = (cam_to_world * vec4(0.0, 0.0, 0.0, 1.0)).xyz;
        vec3 p_far = (cam_to_world * vec4(p_far_view.xyz, 1.0)).xyz;
        vec3 direction = normalize(p_far - origin);

        Ray r;
        r.origin = origin;
        r.t = 1.0/0.0;
        r.inv_direction = 1.0 / direction;

        float unused_depth;
        accumulated_color += trace(r, rng_state, unused_depth);
    }

    // Trace and write
    vec3 final_color = accumulated_color / float(pixel_samples);
    imageStore(output_image, pixel_coords, vec4(final_color, 1.0));
}
